name: Run Unit Tests on Push

on:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    
    - name: restore dependencies
      run: dotnet restore

    - name: Run unit tests
      run: dotnet test